name: feedreader-snap
version: '0.41'
summary: FeedReader is a desktop application to complement  RSS accounts.
description: |
  Mindblowing good description of feedreader the awesome feedreader app.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  feedreader-snap:
    command: desktop-launch feedreader
    plugs: [home, unity7, x11, gsettings, network]


parts:
  feedreader:
    plugin: cmake
    source: https://github.com/jangernert/FeedReader.git
    build-packages:
      - build-essential
      - cmake
      - valac
      - pkg-config
      - gettext
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libjson-glib-dev
      - libwebkit2gtk-4.0-dev
      - libsqlite3-dev
      - libsecret-1-dev
      - libnotify-dev
      - libxml2-dev
      - librest-dev
      - libgee-0.8-dev
      - libcurl4-gnutls-dev
      - libgstreamer-plugins-base1.0-dev
      - libpeas-dev
      - libgoa-1.0-dev
      - libunity-dev
    after: [desktop-gtk3]
